# Generated by Django 2.2 on 2019-04-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogretmenler',
            fields=[
                ('IDogretmen', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad', models.CharField(max_length=50, verbose_name='İsim')),
                ('tel', models.CharField(max_length=10, verbose_name='Tel')),
                ('kullaniciAdi', models.CharField(max_length=25, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(max_length=30, verbose_name='Parola')),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
    ]
